language: cpp
os: xenial
addons:
        apt:
                packages:
                        googletest
                        libgtest-dev
compiler: gcc
before_install: cd emulator&& sudo add-apt-repository universe && sudo apt update && sudo apt install libgtest-dev
